// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAJQW1Z8hkIa2LRPAkdTC2Jmkw9V98cXg',
    appId: '1:577113528629:web:cd35f030514e740898147c',
    messagingSenderId: '577113528629',
    projectId: 'worktime-33fa5',
    authDomain: 'worktime-33fa5.firebaseapp.com',
    databaseURL: 'https://worktime-33fa5-default-rtdb.firebaseio.com',
    storageBucket: 'worktime-33fa5.firebasestorage.app',
    measurementId: 'G-LYKMFETRLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwHjoAlkJQsJ35GUr9qwFkvGpiM2AJyM4',
    appId: '1:577113528629:android:86e536e3184dea4098147c',
    messagingSenderId: '577113528629',
    projectId: 'worktime-33fa5',
    databaseURL: 'https://worktime-33fa5-default-rtdb.firebaseio.com',
    storageBucket: 'worktime-33fa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVQNQlDuvdgKDDeN-dlEuYWZaKErl4wdo',
    appId: '1:577113528629:ios:0f0bfbfe6968d8f898147c',
    messagingSenderId: '577113528629',
    projectId: 'worktime-33fa5',
    databaseURL: 'https://worktime-33fa5-default-rtdb.firebaseio.com',
    storageBucket: 'worktime-33fa5.firebasestorage.app',
    iosBundleId: 'com.ahmad.workTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVQNQlDuvdgKDDeN-dlEuYWZaKErl4wdo',
    appId: '1:577113528629:ios:1c958a05bc1cf6f798147c',
    messagingSenderId: '577113528629',
    projectId: 'worktime-33fa5',
    databaseURL: 'https://worktime-33fa5-default-rtdb.firebaseio.com',
    storageBucket: 'worktime-33fa5.firebasestorage.app',
    iosBundleId: 'com.example.workTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAJQW1Z8hkIa2LRPAkdTC2Jmkw9V98cXg',
    appId: '1:577113528629:web:e6f248272e0836f298147c',
    messagingSenderId: '577113528629',
    projectId: 'worktime-33fa5',
    authDomain: 'worktime-33fa5.firebaseapp.com',
    databaseURL: 'https://worktime-33fa5-default-rtdb.firebaseio.com',
    storageBucket: 'worktime-33fa5.firebasestorage.app',
    measurementId: 'G-78DXD374H0',
  );
}






